### ISSUE TITLE
Migrate to new Python3-based HTPC Manager fork

### ISSUE THREAD

**Issue by MichaIng** [linuxserver/docker-htpcmanager#20]
Due to Python2 EOL and Hellowlol stopped maintaining HTPC Manager, @gmiranda created a fork to port it to Python3, see: https://github.com/Hellowlol/HTPC-Manager/issues/611#issuecomment-671026556

We finally created a GitHub organization based on it to become independent from single "owners" and prevent from getting an abandoned repository > URL > updater again: https://github.com/HTPC-Manager/HTPC-Manager

It generally works fine, however it still needs some tuning and updates, including the modules to fully support 3rd party software updates. Since both of us are not able to actively push development in a reasonable speed, this project urgently requires more contributors.

It would be great if LinuxServer.io would consider switching to the new Python3 based HTPC Manager repository, to make more users aware of it, potentially attract contributors and give this project a future in general.

**Comment by aptalca** [comment]
Thanks for the heads up. We'll certainly look into it. By the way, is it meant to be a drop in replacement for the original?

**Comment by MichaIng** [comment]
Yes it is, apart from the fact that it requires Python 3, but that should not be an issue on any reasonable updated OS.

**Comment by aptalca** [comment]
#21
